model_params:
  name: "VectorVAEnLayers"
  in_channels: 3
  latent_dim: 128
  loss_fn: 'MSE'
  paths: 15
  beta: 0.25
  other_losses_weight: 0.2
  radius: 3
  scale_factor: 1
  learn_sampling: True
  only_auxillary_training: False
  composite_fn: 'soft'
  memory_leak_training: True
  memory_leak_epochs: 50

exp_params:
  dataset: sketchrnn
  data_path: "./data/numbers_changed/"
  img_size: 64
  batch_size: 16 # Better to have a square number
  val_batch_size: 32 # Better to have a square number
  val_shuffle: True
  LR: 0.00075
  weight_decay: 0.0
  scheduler_gamma: 0.75
  grow: False

trainer_params:
  gpus: 1
  max_epochs: 2000

logging_params:
  save_dir: "logs/"
  other_interpolations: True
  name: "VectorVAEnLayers"
  version: 212
  manual_seed: 1265
