model_params:
  name: "VanillaVAE"
  in_channels: 3
  latent_dim: 128
  loss_fn: 'MSE'
  paths: 20
  beta: 1.0
  other_losses_weight: 0.2
  radius: 3
  scale_factor: 1
  learn_sampling: True
  only_auxillary_training: False
  composite_fn: 'soft'
  memory_leak_training: False

exp_params:
  dataset: sketchrnn
  data_path: "./data/baseline_mpl_numbers_changed_vae/"
  img_size: 64
  batch_size: 8 # Better to have a square number
  val_batch_size: 32 # Better to have a square number
  val_shuffle: True
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.75
  grow: False

trainer_params:
  gpus: 1
  max_epochs: 2000

logging_params:
  save_dir: "logs/"
  other_interpolations: True
  name: "VanillaVAE"
  version: 210
  manual_seed: 1265
