model_params:
  name: "VectorVAEnLayers"
  in_channels: 3
  latent_dim: 128
  loss_fn: 'MSE'
  paths: 20
  beta: 0
  radius: 20
  other_losses_weight: 0.5
  scale_factor: 1
  learn_sampling: True
  only_auxillary_training: False
  composite_fn: 'soft'
  memory_leak_training: False

exp_params:
  dataset: sketchrnn
  data_path: "./data/8_3c_corrupted/"
  img_size: 128
  batch_size: 4 # Better to have a square number
  val_batch_size: 16 # Better to have a square number
  val_shuffle: True
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.75
  grow: False

trainer_params:
  gpus: 1
  max_epochs: 2500

logging_params:
  save_dir: "logs/"
  other_interpolations: True
  name: "VectorVAEnLayers"
  version: 701
  manual_seed: 1265
