model_params:
  name: 'VectorVAEMNIST'
  in_channels: 1
  latent_dim: 128
  loss_fn: 'MSE'

exp_params:
  dataset: MNIST
  data_path: "./data/"
  img_size: 32
  batch_size: 128 # Better to have a square number
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 500
  max_epochs: 300

logging_params:
  save_dir: "logs/"
  name: "VectorVAEMNIST"
  manual_seed: 1265
  version: 72
  resume:
