model_params:
  name: 'VectorVAE'
  in_channels: 3
  latent_dim: 128
  loss_fn: 'MSE'
  paths: 20
  beta: 0
  radius: 5
  scale_factor: 20
  learn_sampling: False
  auxillary_training: True

exp_params:
  dataset: sketchrnn
  data_path: "./data/7/"
  img_size: 128
  batch_size: 8 # Better to have a square number
  LR: 0.00075
  weight_decay: 0.0
  scheduler_gamma: 0.95
  grow: True

trainer_params:
  gpus: 1
  max_nb_epochs: 1000
  max_epochs: 300

logging_params:
  save_dir: "logs/"
  other_interpolations: True
  name: "VectorVAE"
  version: 103
  manual_seed: 1265
  resume:
